### ISSUE TITLE
[Forge 1.20.1] Coffee Delight causing world crash on new world creation and when loading existing worlds.

### ISSUE THREAD

**Issue by NovaLynxie** [AmarokIce/CoffeeDelight#8]
Hi there!

I have been experiencing crashing problems with your mod addon and Farmer's Delight in Forge 1.20.1
It is preventing world creation, and when adding the mod addon afterwards prevents existing worlds loading at all.
After removing the mod in both cases, the worlds load correctly.

Forge & Mod Versions:
- Forge 1.20.1 47.2.0
- CoffeeDelight-Forge-1.4.jar
- FarmersDelight-1.20.1-1.2.3.jar

Here is my crash report from trying to create a world with this mod installed:
[crash-2023-10-26_14.02.11-client.txt](https://github.com/AmarokIce/CoffeeDelight/files/13177725/crash-2023-10-26_14.02.11-client.txt)
This is the log obtained while loading the world with the mod addon added after successfully creating a world with just Farmer's Delight and no other addons to confirm this addon was causing the problem.
[2023-10-26-7.log](https://github.com/AmarokIce/CoffeeDelight/files/13177821/2023-10-26-7.log)

After digging into the log file after re-adding the addon once a world file was successfully created for testing, it revealed this:
```log
...
[14:06:40] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[14:06:41] [Render thread/ERROR]: Registry loading errors:
> Errors in registry minecraft:root:
>> Errors in element minecraft:worldgen/placed_feature:
java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/placed_feature]: [coffee_delight:wild_coffee_bush_patch]
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.m_203521_(MappedRegistry.java:331)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_257131_(RegistryDataLoader.java:69)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_247207_(RegistryDataLoader.java:65)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_246152_(WorldLoader.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_245736_(WorldLoader.java:58)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:31)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_246486_(WorldOpenFlows.java:162)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:113)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:181)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:169)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:65)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:575)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:474)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:413)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92)
...
```

**Comment by Corosauce** [comment]
Happening for me too.

**Comment by AmarokIce** [comment]
Sorry Im late, and now fix it soon
